services:
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: abc123
            POSTGRES_DB: kane-blog
            PGUSER: postgres
        networks:
            - data_net
        command: postgres -N 500
        ports:
            - 5439:5432
        volumes:
            - type: tmpfs
              target: /var/lib/postgresql/data
    localstack:
        image: localstack/localstack
        environment:
            SERVICES: "s3, sqs, opensearch, sns"
            HOSTNAME: localstack
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
        networks:
            - data_net
        ports:
            - "[::1]:4599:4566"
            - "127.0.0.1:4599:4566"
            - "127.0.0.1:4710-4759:4710-4759"
        volumes:
            - "./scripts/localstack:/etc/localstack/init/ready.d"
    api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - PORT=5000
            - NODE_ENV=production
            # Override to point to localstack container in the docker network
            - AWS_S3_ENDPOINT=http://localstack:4566
            - AWS_S3_EXTERNAL_ENDPOINT=http://localhost:4599
        ports:
            - "5000:5000"
        depends_on:
            - localstack
        networks:
            - data_net
        # Simulate AWS ECS Fargate CPU & RAM limitations (0.5 vCPU, 1GB RAM)
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1024M

volumes:
    cache:
        driver: local

networks:
    data_net:
        name: data_net
